### ISSUE TITLE
Devenv.com: Command Not Found

### ISSUE THREAD

**Issue by danyeaw** [preshing/cairo-windows#1]
Thanks so much for sharing this with the community ❤️ 

I am trying to follow the steps you laid out here and I also referenced the cairo end-to-end build win32 instructions. I installed Visual Studio Build Tools 2017, and then after that tried to install Visual Studio Community 2017 as well. I am getting the following error:

`build-cairo-windows.sh: line 69: devenv.com: command not found`
`FAILED COMMAND: devenv.com "projects\vstudio\vstudio.sln" -upgrade`

Is there something different I need to install to get devenv.com? Do I need to get an older version of Microsoft Visual C++ Studio Express? I tried looking it up, but I had a hard time finding good information. Thanks!

**Comment by zwcloud** [comment]
devenv.com is next to devenv.exe:
![image](https://user-images.githubusercontent.com/6965758/50039238-72da8380-0069-11e9-8ecd-d6856716c4a3.png)

**Comment by preshing** [comment]
Did you open "x86 Native Tools Command Prompt for VS 2017" as mentioned in the README, or did you open a regular command prompt? The former should work because devenv.com will be found in your PATH; the latter won't.

**Comment by danyeaw** [comment]
@preshing and @zwcloud thanks for your response!

Yes I am using the x86 Native Tools Command Prompt for VS 2017:
![cmd_prompt](https://user-images.githubusercontent.com/10014976/50103898-b0b8e280-01f6-11e9-976c-84fa20988d3c.PNG)
I also see the devenv.com in my installation directory as well:
![windows_explorer](https://user-images.githubusercontent.com/10014976/50103946-d6de8280-01f6-11e9-82eb-1e4ba20e15b4.PNG)

Also if I type `path` from the same x86 Native Tools Command Prompt, the `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE` path is listed

**Comment by danyeaw** [comment]
One other thing, on that first screenshot it says whereis command not found. If I do the `set path=C:\msys32\usr\bin;%PATH%` command, then that error goes away, but the devenv.com error is still present. I didn't want that to cause confusion that this whereis error may be part of the problem.

**Comment by preshing** [comment]
Just a guess... Maybe you already have a previously installed `sh` somewhere, and it has a startup script that is overriding the path.

When you open a new x86 Native Tools Command Prompt, what's the output of `where sh`?

When you open a new x86 Native Tools Command Prompt, what happens when you run `devenv.com /?`?

Once you've opened a `sh` shell, what's the output of `echo $PATH`? Is `/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE` (or similar) listed?

Is the output of `echo $PATH` any different depending on whether you run `set PATH=C:\msys32\usr\bin;%PATH%` (as the README says) before opening the `sh` shell?

**Comment by danyeaw** [comment]
@preshing I have windows-git installed in addition to msys2, so `where sh` on a new x86 Native Tools Command Prompt returns `C:\Program Files\Git\usr\bin\sh.exe`. If I set the path to include the msys32 directory, then I get:
`C:\msys32\usr\bin\sh`
`C:\Program Files\Git\usr\bin\sh.exe`

The difference without set path is that I have the following lines:
`/cmd`
`/mingw64/bin`
`/usr/bin`

With the path set I have these instead:
`/c/Program Files/Git/cmd`
`/c/Program Files/Git/mingw64/bin`
`/c/Program Files/Git/usr/bin`

and the addition of `/usr/bin`

The Visual Studio paths are there for both:
`/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/HostX86/x86`
`/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/IDE/CommonExtensions/Microsoft/TestWindow`
`/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/bin/Roslyn`
`/c/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86`
`/c/Program Files (x86)/Windows Kits/10/bin/x86`
`/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/bin`
`/c/Windows/Microsoft.NET/Framework/v4.0.30319`
`/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/IDE`
`/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/Tools`


Do you think the issue is that windows-git is conflicting with msys2?

**Comment by danyeaw** [comment]
Update: I removed windows-git and restarted all the command prompts fresh. I am getting the same error, so that didn't seem to be the issue.

**Comment by preshing** [comment]
So when you open a new x86 Native Tools Command Prompt, what happens when you just run:

    devenv.com /?

**Comment by danyeaw** [comment]
@preshing 
`>devenv.com /?`
`'devenv.com' is not a recognized as an internal or external command, operable program or batch file.`

**Comment by zwcloud** [comment]
@danyeaw Start the *x86 Native Tools Command Prompt* from here:

![image](https://user-images.githubusercontent.com/6965758/50165337-b52cea80-031f-11e9-95f1-3b74f9576d26.png)

Then input `devenv.com /?`, press Enter. For me, it displays:

![image](https://user-images.githubusercontent.com/6965758/50165428-f32a0e80-031f-11e9-83fc-31268a5d76a6.png)

If `devenv.com` is the only thing needed by cairo-windows, then adding it to the PATH environment variable should fix your issue. The cmd.exe need to be closed and re-opened to make the new PATH working.

**Comment by danyeaw** [comment]
@zwcloud Yes, that is the exact process I followed

![capture](https://user-images.githubusercontent.com/10014976/50166300-c7be0a00-02b4-11e9-886c-b0459239351c.PNG)

**Comment by zwcloud** [comment]
It seems your VS2017 installation is broken and the version 15.0 is outdated. Try updating VS2017 to latest.

**Comment by danyeaw** [comment]
My initial installation of VS2017 was just last week. I uninstalled all of Visual Studio and Visual Studio Build Tools just now. I then reinstalled both using choco this time. Then I added the Visual C++ build tools Workload to Visual Studio Build Tools. I have VS Community 2017 and VS Build Tools version 15.9.4 installed.

![capture2](https://user-images.githubusercontent.com/10014976/50172976-3e163880-02c4-11e9-8a74-39c4a2fa2ef9.PNG)
![capture](https://user-images.githubusercontent.com/10014976/50172898-13c47b00-02c4-11e9-808d-e2c1a2ac8ea7.PNG)

 I rebooted my computer following installation and I am getting the exact same error. `devenv.com` is found when I use the Developer Command Prompt for VS 2017, but not for either the x86 or x64 Native Tools Command Prompt.

Is there some other Workload or Individual component I need to install in my build tools?

**Comment by preshing** [comment]
What happens when you do the same thing, but replace `.com` with `.exe`?

Open a new x86 Native Tools Command Prompt and just run:

    devenv.exe /?

**Comment by danyeaw** [comment]
@preshing
`devenv.exe /?`
`'devenv.exe' is not a recognized as an internal or external command, operable program or batch file.`

**Comment by preshing** [comment]
There is something inconsistent in your replies. You said that when you type `path` from the x86 Native Tools Command Prompt, the following path is listed:

    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE

But in a later answer, you said that when you typed `echo $PATH` at the msys2 prompt, this path was listed instead:

    /c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/IDE

Note that (besides the formatting) these are **not** the same path. The first contains "Community" but the second contains "BuildTools". You should double-check the first one (just type `path` from the x86 Native Tools Command Prompt).

**Comment by danyeaw** [comment]
@preshing @zwcloud Thanks for your attempt to help, I really appreciate it. I think the use of bash scripting is slightly fragile to install versions as Microsoft updates their tools. I am going to try to use [gvsbuild](https://github.com/wingtk/gvsbuild) instead, and close this issue.

**Comment by uday1kiran** [comment]
Same issue exists with 2019 version also.
Any resolution for this, all the above steps are not useful.

**Comment by riyazmuthyalapati** [comment]
there is no devenv file in my path.. can somebody please help ?

assert os.path.isfile( devenv), f'Does not exist: {devenv}'
      AssertionError: Does not exist: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\devenv.com
