### ISSUE TITLE
Chinese characters? I'm using this with wxWidgets.

### ISSUE THREAD

**Issue by tonyvsuk** [preshing/cairo-windows#15]
Hello all,

First, thanks for this. I'm using it as a renderer in a wxWidgets application, it's much faster than the default, 2D and GDI+ renderers.

One of our users has reported a problem. They use Chinese characters 易感者, which just display as three square boxes when using Cairo. I've searched the web, and found an old post saying they had trouble with Chinese characters. But found another post saying Chinese characters were fine. Japanese characters also display as square boxes, so I'm guessing it's a unicode problem. They all display fine using the other renderers provided in wxWidgets.

Could this be an issue with Cairo or maybe the way it's built?

Thanks in advance,

Tony.

![image](https://user-images.githubusercontent.com/15376993/134332255-3097a74a-d5da-4867-ad83-f2dbd3fce203.png)

**Comment by preshing** [comment]
Sorry, I'm not a cairo developer. I just built the lib. Best reach out with the cairo community.
