### ISSUE TITLE
Zlib compile failed

### ISSUE THREAD

**Issue by AlexHewJW** [preshing/cairo-windows#16]
I tried to compile for x86 but zlib failed.

 error C2220: the following warning is treated as an error
1>C:\msys64\home\wasd\zlib\infback.c(622,9): warning C4061: enumerator 'HEAD' in switch of enum 'inflate_mode' is not explicitly handled by a case label
1>C:\msys64\home\wasd\zlib\inflate.h(20): message : see declaration of 'inflate_mode'
1>C:\msys64\home\wasd\zlib\infback.c(622,9): warning C4061: enumerator 'FLAGS' in switch of enum 'inflate_mode' is not explicitly handled by a case label
1>C:\msys64\home\wasd\zlib\inflate.h(20): message : see declaration of 'inflate_mode'
1>C:\msys64\home\wasd\zlib\infback.c(622,9): warning C4061: enumerator 'TIME' in switch of enum 'inflate_mode' is not explicitly handled by a case label

Here are part of the error codes, please help. Thank you.

**Comment by preshing** [comment]
Sorry, I'm not able to help you with that. Good luck.
