### ISSUE TITLE
pdf is created but blank

### ISSUE THREAD

**Issue by gilboonet** [preshing/cairo-windows#17]
Thanks for your project that works fine, except for pdf. I tried with success png and svg backends (from Zetcode cairo graphics tutorial), but didn't manage to make pdf backend work, it only creates a blank file that has 0 pages. Is there something that need to be added to have pdf support ?

**Comment by preshing** [comment]
Not sure. One way to get an idea of what could be wrong is to try building cairo from sources on Linux, keeping an eye on the configuration options it exposes...

**Comment by gilboonet** [comment]
I didn't try cairo-windows on linux because I already have Cairo lib working there, but I will try. I'mporting to windows a linux c console program that creates a multipage pdf file.

**Comment by gilboonet** [comment]
> Not sure. One way to get an idea of what could be wrong is to try building cairo from sources on Linux, keeping an eye on the configuration options it exposes...

I just made the same on Ubuntu, and it was ok for the pdf backend. As I used latest cairo-version on it, I also updated my windows version, thinking it could make it work, but if didn't. I'm not experienced enough to be able to trace configuration options that it exposes, it might be into the built directory.
Here is the output I had on Ubuntu : 
- (base) gilb-r@gilboone:/mnt/GIGI/docu2/CairoSample/build$ make
Consolidate compiler generated dependencies of target CairoSample
- [ 50%] Linking C executable CairoSample
- [100%] Built target CairoSample
- (base) gilb-r@gilboone:/mnt/GIGI/docu2/CairoSample/build$ cmake ..
- -- Configuring done
- -- Generating done
- -- Build files have been written to: /mnt/GIGI/docu2/CairoSample/build

I attach a file called 'CMakeOutput.log'
[CMakeOutput.log](https://github.com/preshing/cairo-windows/files/9339386/CMakeOutput.log)

**Comment by gilboonet** [comment]
What's happening is that as soon as I run "cairo_show_page(..)" an "out of memory" error occurs even if i didn't do anything on the pdf surface., so it's not an error from cairo_windows but a memory leak from cairo with PDF surfaces.

I finally found a way to make it work by replacing the extern resources by resources from my current gtk build, cairo 16.2.0 and other dll it needs.
