### ISSUE TITLE
Automatic dependency update chat

### ISSUE THREAD

**Issue by stuaxo** [preshing/cairo-windows#5]
I had a look into some github bots that can update dependencies to see if they can help here.
In the end dependencies.io looked like the best, as they can update system dependencies, not just python or ruby libraries.es.

There are two parts, a CLI tool, which doesn't require an API key, and a github workflow, which does.

These both read a yaml file that describes dependencies.

Getting an API key needs a license, which can be purchased, + there is a form which open source projects can apply for a free license from, I filled this in and @davegaeddert was super helpful.

**Comment by stuaxo** [comment]
Once the deps.yml is confirmed to be working, it's possible to add a github workflow that can generate PRs using dependencies.io
You can set the github workflow to run on a schedule, and I was able to set it up respond to a webhook too, so a correctly crafted curl command could trigger the workerflow as needed.

The PRs are one per library updated, you can see examples here:
https://github.com/stuaxo/cairo-windows/pulls
![image](https://user-images.githubusercontent.com/179677/90250713-6a38e280-de34-11ea-9ea9-2552eacd93b3.png)

This is dependent on getting a license for dependencies.io

**Comment by preshing** [comment]
That's interesting. I merged it. Thanks for the contribution!

I see the yaml file fetches version numbers from places that aren't necessarily in sync with the download sources used by the script itself, but I guess it's good enough for this project.

You know what would also be great: Instead of running this script using MSYS2 on Windows (as I currently do), get a Docker image that can run MSVC using Wine and modify the script to run in that environment. Ideally the whole build process could be turned into a one-click thing. Maybe even built automatically from a GitHub action (if that's possible).

**Comment by stuaxo** [comment]
> I see the yaml file fetches version numbers from places that aren't necessarily in sync with the download sources used by the script itself, but I guess it's good enough for this project.

This is true.  

The deps tool has a backend for git `deps-git`, but would need something like `deps-web` that could parse the web directory at https://www.cairographics.org/releases/

There is small danger of a race condition if this runs when git is updated but the release hasn't been uploaded yet.

> ...  Docker image that can run MSVC using Wine and modify the script to run in that environment. Ideally the whole build process could be turned into a one-click thing. Maybe even built automatically from a GitHub action (if that's possible).

Running from docker in linux would be nice, it's not needed for running under github actions, or travis as they support windows natively.

I've only been using github actions for this thing, so pretty new to it, I think the one click thing is possible, even without it webhooks are, so pasting something into cURL or using postman is good approximation.

**Comment by stuaxo** [comment]
I think you don't need wine, you can install mingw on Linux and compile with it: 
https://stackoverflow.com/questions/2033997/how-to-compile-for-windows-on-linux-with-gcc-g

**Comment by stuaxo** [comment]
Turns out deps wasn't updating as I already had another branch with the update on it, they are going to add a message in that case.

**Comment by stuaxo** [comment]
Last bit will be https://github.com/preshing/cairo-windows/pull/9
